### ISSUE TITLE
Return Http 400 (Bad Request) for malformed POST requests

### ISSUE THREAD

**Issue by Williangalvani** [patrickelectric/mavlink2rest#10]
Right now it seems to respond with 404, which is misleading, [400](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) makes more sense

**Comment by patrickelectric** [comment]
That should be the behavior, please provide a minimum `curl` or python example that can replicate the problem

**Comment by Williangalvani** [comment]
It seems that I was using the wrong endpoint, oops!
