### ISSUE TITLE
Consider adding CORS policies to allow access from different origins

### ISSUE THREAD

**Issue by Williangalvani** [patrickelectric/mavlink2rest#12]
This is necessary to access the API from the browser without extra work.
See https://discuss.bluerobotics.com/t/rest-api-cors-blocked/7574

**Comment by patrickelectric** [comment]
I have a wip build, will update it soon

**Comment by patrickelectric** [comment]
Fixed in 0.7.2

**Comment by noahbliss** [comment]
Perhaps I am an idiot, but is this still fixed? I am using the latest version and have these issues currently. 

Just to test, I pulled down version 0.7.2 and do not experience this issue.
